import { TASKS } from '~configs'

export const FIRST_ROW_TASK_CARD_TOP = TASKS.TREE_STRUCTURE.MARGIN.ROW + TASKS.TREE_STRUCTURE.MARGIN.CARD.VERTICAL
export const EACH_TASK_CARD_WITH_MARGIN_HEIGHT =
  TASKS.TREE_STRUCTURE.CARD.HEIGHT + TASKS.TREE_STRUCTURE.MARGIN.CARD.VERTICAL * 2 + TASKS.TREE_STRUCTURE.MARGIN.ROW
export const EACH_TASK_CARD_WITH_MARGIN_WIDTH = TASKS.TREE_STRUCTURE.CARD.WIDTH + TASKS.TREE_STRUCTURE.MARGIN.CARD.SIDE * 2

export const getFrameWidth = (count: number, ratio: number) =>
  (count * EACH_TASK_CARD_WITH_MARGIN_WIDTH + (count + 1) * TASKS.TREE_STRUCTURE.MARGIN.COLUMN) * ratio
export const getFrameHeight = (count: number, ratio: number) =>
  (count * EACH_TASK_CARD_WITH_MARGIN_HEIGHT + (count + 1) * TASKS.TREE_STRUCTURE.MARGIN.ROW) * ratio
